### ISSUE TITLE
Images paths

### ISSUE THREAD

**Issue by annaoleksiuk** [tsawler/laravel-filemanager#25]
I have some troubles with paths in Controllers, especially Resize and Crop. E.g. when I try to resize, image doesn't appear and it's source looks like: 
`http://localhost/vendor/laravel-filemanager/images///image.jpg`, when there is no folder, 
and `http://localhost/vendor/laravel-filemanager/images/folder/image.jpg`. 
Shouldn't therefore $dir variable deal with slashes? Controllers is quite readable, but still - should they deal with all that logic? 

I know, I've mentioned you about my paths issues a while ago, but I wasn't specific and I still don't know if it was only me, or is it more general problem. Wouldn't be cleaner to make even some class handling paths, so we would always know where we are? It would also give code some flexibility when paths should be changed.

I have also other question - was the filemanager designed to work only with one folder "level"?

**Comment by Younesi** [comment]
First, Thanks for your awesome package, I really appreciate what you have done.
I have such problem while my images don't get shown.
It seems they don't get loaded  either
The error on browser is: 
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Younesi** [comment]
In order to get  correct path just change urls in config file to the following:
images_url'         => '/public/vendor/laravel-filemanager/images/'
    'files_url'          => '/public/vendor/laravel-filemanager/files/'
As you might notice I have only added "/public" to default ones.
