### ISSUE TITLE
"illuminate/html": "5.*" and namespaces

### ISSUE THREAD

**Issue by adrianoGaspar** [tsawler/laravel-filemanager#34]
Hello,  "illuminate/html": "5.*"  is necessary, but from laravel 5 does not come more by default. My suggestion is that this place dependence on composer or delete the code.

Another point is in relation to the namespace of the controllers: if the application has an App different namespace the application does not meet the comtrollers, I had to change on hand.

**Comment by tsawler** [comment]
Hi:

I've added "laravelcollective/html": "5.1.*" (the successor to illuminate/html) to composer.json. Not sure what to do about the namespace issue, but will look into it when time permits.
