### ISSUE TITLE
Automaticly adding thumbs prefix

### ISSUE THREAD

**Issue by rorc** [tsawler/laravel-filemanager#35]
In config i use images_url => '/img/', but manager generating src /img/**thumbs**/imageName
Is it not configurable?
In images.blade.php i found hardcode...
`                        <img id="{!! $file !!}"
                             src="{{ $dir_location }}{{ $base }}/thumbs/{{ basename($file) }}?r={{ str_random(40) }}"
                             alt="">`

**Comment by tsawler** [comment]
No, it's not configurable. Fee free to issue a pull request to make it configurable, though.
