### ISSUE TITLE
Cannot list uploaded images

### ISSUE THREAD

**Issue by gmagnenat** [tsawler/laravel-filemanager#36]
The images are uploading correctly. I see them in the corresponding folders.
But nothing shows up in the file manager. When uploading a picture the page doesn't refresh and keep saying it's uploading.

![capture d ecran 2015-08-23 a 13 43 10](https://cloud.githubusercontent.com/assets/924127/9428065/025320d0-499d-11e5-9537-709111e19e43.png)

I get this error in the browser console
```code
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**Comment by marionava** [comment]
I have the exactly the same issue. Any solution?

**Comment by kamran7293** [comment]
i have this issue too, somebody help us ! i have been searched for it for a week, no solution yet.

**Comment by jvv** [comment]
See:
- Requires "intervention/image": "2.*"

It's not described pretty clear in the readmy of this package, but you should read up on: http://image.intervention.io/getting_started/installation#laravel to make it all work.

**Comment by kamran7293** [comment]
Thanks a lot jvv, i added 'Intervention\Image\ImageServiceProvider' to providers and        'Intervention\Image\Facades\Image' to alias but the problem exists yet. 
there is a point that makes me confused. website works well at local and that blasted error will disappear if i remove uploaded folders and create them again, but it's not work on the server. the related folder permissions also had been set to 755.

**Comment by marionava** [comment]
I fixed this using the file generated with ```php artisan vendor:publish --tag=lfm_config```.

I only reviewed the correct path on the config/lfm.php file and I had an error. After fixed, everything worked fine.

**Comment by kamran7293** [comment]
according to dear jvv answer, i found the solution. you should enable PHP modules which required by Laravel File Manager requirements like fileinfo,gd and imagick.

**Comment by tsawler** [comment]
You just need gd, but not imagick. You can, of course, use imagick.

Since lfm uses intervention/image, it requires the same php functionality.

**Comment by habatmu-birhanu** [comment]
Hello guys, currently I'm developing application with laravel and i have used this package called laravel file manager with tinymce. and when i click insert image button on tinymce editor i got this error in the console
GET http://localhost:8000/login 404 (Not Found) ..i think the problem is is i use this package called Cartlyast sentinel instead of default authentication package shipped with laravel.... so how do i solve this probelem..any suggestion is much appreciated.
