### ISSUE TITLE
Not show correct link

### ISSUE THREAD

**Issue by nhanco** [tsawler/laravel-filemanager#43]
When i use with CKeditor it's not show correct image link. 
that show /filemanager/F:\Nhan\www\bimpublic/files/user1/60534_10202890948611141_1769156736_n.jpg
it's cant not display. and wrong path correct path is nhan/www/bim/public

**Comment by tsawler** [comment]
There is not enough information for me to give a useful response. However, it rather looks like you have your path set incorrectly in the lfm config file. I've installed this on dozens of project and have not seen the issue you describe.
