### ISSUE TITLE
Package doesn't work when using custom namespace.

### ISSUE THREAD

**Issue by Nikita240** [tsawler/laravel-filemanager#44]
```php
<?php namespace Tsawler\Laravelfilemanager\controllers;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\View;
use Intervention\Image\Facades\Image;

/**
 * Class LfmController
 * @package Tsawler\Laravelfilemanager\controllers
 */
class LfmController extends Controller {
}
```

All the controllers reference the parent controller with `use App\Http\Controllers\Controller;`. This doesn't work when you have a custom namespace, as the controller file no longer resolves through the `App` namespace.

`
PHP Fatal error:  Class 'App\Http\Controllers\Controller' not found in dir/vendor/tsawler/laravel-filemanager/src/controllers/LfmController.php on line 15
`

**Comment by tsawler** [comment]
Feel free to modify this and issue a pull request.
