### ISSUE TITLE
User has to login again when accessing the file manager

### ISSUE THREAD

**Issue by rrolt** [tsawler/laravel-filemanager#52]
Hi,

If the user is already logged in, when he opens the file manager via CKEditor, he has to login again because the session isn't conserved.

Should I use a cookie? Is there another way?

Thanks.

**Comment by rrolt** [comment]
Fixed it by importing the routes into my own file. The sessions now work. Really strange.

**Comment by tsawler** [comment]
Hi:

I just added this to a vanilla Laravel 5.2 install, dropped in a simple Auth screen, tried logging in and firing up LFM without issue...

I am, however, glad to hear that you got it working.
