### ISSUE TITLE
Package always view the files Directory

### ISSUE THREAD

**Issue by AmrAlfoly** [tsawler/laravel-filemanager#56]
i am using your package with ckeditor but i have an issue :
when i press the image button in ckeditor  your filemanager appear with this url on top 
`http://elfergany.dev/laravel-filemanager?type=Images&CKEditor=body&CKEditorFuncNum=1&langCode=ar`
as you can see the type is image but it browses the files Directory
![image](https://cloud.githubusercontent.com/assets/11133091/12737194/25815152-c95f-11e5-8396-d5b574a8bb71.png)

**Comment by rebootcode** [comment]
How are you using filemanager, I am always redirected to "public" directory ?
